// Mocks generated by Mockito 5.4.6 from annotations
// in hosta/test/mocks/mock_annotation.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i6;
import 'dart:typed_data' as _i8;

import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i11;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i12;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i14;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i17;
import 'package:flutter_local_notifications/src/platform_specifics/ios/enums.dart'
    as _i16;
import 'package:flutter_local_notifications/src/types.dart' as _i18;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i13;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i9;
import 'package:socket_io_client/src/manager.dart' as _i3;
import 'package:socket_io_client/src/socket.dart' as _i4;
import 'package:socket_io_common/src/util/event_emitter.dart' as _i10;
import 'package:timezone/timezone.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeManager_2 extends _i1.SmartFake implements _i3.Manager {
  _FakeManager_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocket_3 extends _i1.SmartFake implements _i4.Socket {
  _FakeSocket_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i6.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i8.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
          )
          as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i5.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_1(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i9.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i5.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Socket].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocket extends _i1.Mock implements _i4.Socket {
  MockSocket() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get nsp =>
      (super.noSuchMethod(
            Invocation.getter(#nsp),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#nsp)),
          )
          as String);

  @override
  _i3.Manager get io =>
      (super.noSuchMethod(
            Invocation.getter(#io),
            returnValue: _FakeManager_2(this, Invocation.getter(#io)),
          )
          as _i3.Manager);

  @override
  _i4.Socket get json =>
      (super.noSuchMethod(
            Invocation.getter(#json),
            returnValue: _FakeSocket_3(this, Invocation.getter(#json)),
          )
          as _i4.Socket);

  @override
  num get ids =>
      (super.noSuchMethod(Invocation.getter(#ids), returnValue: 0) as num);

  @override
  Map<dynamic, dynamic> get acks =>
      (super.noSuchMethod(
            Invocation.getter(#acks),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  bool get connected =>
      (super.noSuchMethod(Invocation.getter(#connected), returnValue: false)
          as bool);

  @override
  bool get disconnected =>
      (super.noSuchMethod(Invocation.getter(#disconnected), returnValue: false)
          as bool);

  @override
  List<dynamic> get sendBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#sendBuffer),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> get receiveBuffer =>
      (super.noSuchMethod(
            Invocation.getter(#receiveBuffer),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<dynamic, dynamic> get flags =>
      (super.noSuchMethod(
            Invocation.getter(#flags),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  bool get active =>
      (super.noSuchMethod(Invocation.getter(#active), returnValue: false)
          as bool);

  @override
  set nsp(String? value) => super.noSuchMethod(
    Invocation.setter(#nsp, value),
    returnValueForMissingStub: null,
  );

  @override
  set opts(Map<dynamic, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#opts, value),
    returnValueForMissingStub: null,
  );

  @override
  set io(_i3.Manager? value) => super.noSuchMethod(
    Invocation.setter(#io, value),
    returnValueForMissingStub: null,
  );

  @override
  set json(_i4.Socket? value) => super.noSuchMethod(
    Invocation.setter(#json, value),
    returnValueForMissingStub: null,
  );

  @override
  set ids(num? value) => super.noSuchMethod(
    Invocation.setter(#ids, value),
    returnValueForMissingStub: null,
  );

  @override
  set acks(Map<dynamic, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#acks, value),
    returnValueForMissingStub: null,
  );

  @override
  set connected(bool? value) => super.noSuchMethod(
    Invocation.setter(#connected, value),
    returnValueForMissingStub: null,
  );

  @override
  set disconnected(bool? value) => super.noSuchMethod(
    Invocation.setter(#disconnected, value),
    returnValueForMissingStub: null,
  );

  @override
  set sendBuffer(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#sendBuffer, value),
    returnValueForMissingStub: null,
  );

  @override
  set receiveBuffer(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#receiveBuffer, value),
    returnValueForMissingStub: null,
  );

  @override
  set query(String? value) => super.noSuchMethod(
    Invocation.setter(#query, value),
    returnValueForMissingStub: null,
  );

  @override
  set auth(dynamic value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  set subs(List<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#subs, value),
    returnValueForMissingStub: null,
  );

  @override
  set flags(Map<dynamic, dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#flags, value),
    returnValueForMissingStub: null,
  );

  @override
  set id(String? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set pid(String? value) => super.noSuchMethod(
    Invocation.setter(#pid, value),
    returnValueForMissingStub: null,
  );

  @override
  set lastOffset(String? value) => super.noSuchMethod(
    Invocation.setter(#lastOffset, value),
    returnValueForMissingStub: null,
  );

  @override
  void subEvents() => super.noSuchMethod(
    Invocation.method(#subEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Socket open() =>
      (super.noSuchMethod(
            Invocation.method(#open, []),
            returnValue: _FakeSocket_3(this, Invocation.method(#open, [])),
          )
          as _i4.Socket);

  @override
  _i4.Socket connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _FakeSocket_3(this, Invocation.method(#connect, [])),
          )
          as _i4.Socket);

  @override
  _i4.Socket send(List<dynamic>? args) =>
      (super.noSuchMethod(
            Invocation.method(#send, [args]),
            returnValue: _FakeSocket_3(this, Invocation.method(#send, [args])),
          )
          as _i4.Socket);

  @override
  void emit(String? event, [dynamic data]) => super.noSuchMethod(
    Invocation.method(#emit, [event, data]),
    returnValueForMissingStub: null,
  );

  @override
  void emitWithAck(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #emitWithAck,
      [event, data],
      {#ack: ack, #binary: binary},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void packet(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#packet, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onopen([dynamic _0]) => super.noSuchMethod(
    Invocation.method(#onopen, [_0]),
    returnValueForMissingStub: null,
  );

  @override
  void sendConnectPacket(Map<dynamic, dynamic>? data) => super.noSuchMethod(
    Invocation.method(#sendConnectPacket, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void onerror(dynamic err) => super.noSuchMethod(
    Invocation.method(#onerror, [err]),
    returnValueForMissingStub: null,
  );

  @override
  void onclose(dynamic reason) => super.noSuchMethod(
    Invocation.method(#onclose, [reason]),
    returnValueForMissingStub: null,
  );

  @override
  void onpacket(dynamic packet) => super.noSuchMethod(
    Invocation.method(#onpacket, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onevent(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#onevent, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  Function ack(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#ack, [id]), returnValue: () {})
          as Function);

  @override
  void onack(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
    Invocation.method(#onack, [packet]),
    returnValueForMissingStub: null,
  );

  @override
  void onconnect(dynamic id, dynamic pid) => super.noSuchMethod(
    Invocation.method(#onconnect, [id, pid]),
    returnValueForMissingStub: null,
  );

  @override
  void emitBuffered() => super.noSuchMethod(
    Invocation.method(#emitBuffered, []),
    returnValueForMissingStub: null,
  );

  @override
  void ondisconnect() => super.noSuchMethod(
    Invocation.method(#ondisconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void destroy() => super.noSuchMethod(
    Invocation.method(#destroy, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Socket close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _FakeSocket_3(this, Invocation.method(#close, [])),
          )
          as _i4.Socket);

  @override
  _i4.Socket disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _FakeSocket_3(
              this,
              Invocation.method(#disconnect, []),
            ),
          )
          as _i4.Socket);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Socket compress(dynamic compress) =>
      (super.noSuchMethod(
            Invocation.method(#compress, [compress]),
            returnValue: _FakeSocket_3(
              this,
              Invocation.method(#compress, [compress]),
            ),
          )
          as _i4.Socket);

  @override
  void on(String? event, _i10.EventHandler<dynamic>? handler) =>
      super.noSuchMethod(
        Invocation.method(#on, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void once(String? event, _i10.EventHandler<dynamic>? handler) =>
      super.noSuchMethod(
        Invocation.method(#once, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void onAny(_i10.AnyEventHandler<dynamic>? handler) => super.noSuchMethod(
    Invocation.method(#onAny, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  void off(String? event, [_i10.EventHandler<dynamic>? handler]) =>
      super.noSuchMethod(
        Invocation.method(#off, [event, handler]),
        returnValueForMissingStub: null,
      );

  @override
  void offAny([_i10.AnyEventHandler<dynamic>? handler]) => super.noSuchMethod(
    Invocation.method(#offAny, [handler]),
    returnValueForMissingStub: null,
  );

  @override
  void clearListeners() => super.noSuchMethod(
    Invocation.method(#clearListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  bool hasListeners(String? event) =>
      (super.noSuchMethod(
            Invocation.method(#hasListeners, [event]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i11.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool?> initialize(
    _i12.InitializationSettings? initializationSettings, {
    _i13.DidReceiveNotificationResponseCallback?
    onDidReceiveNotificationResponse,
    _i13.DidReceiveBackgroundNotificationResponseCallback?
    onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [initializationSettings],
              {
                #onDidReceiveNotificationResponse:
                    onDidReceiveNotificationResponse,
                #onDidReceiveBackgroundNotificationResponse:
                    onDidReceiveBackgroundNotificationResponse,
              },
            ),
            returnValue: _i5.Future<bool?>.value(),
          )
          as _i5.Future<bool?>);

  @override
  _i5.Future<_i13.NotificationAppLaunchDetails?>
  getNotificationAppLaunchDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationAppLaunchDetails, []),
            returnValue: _i5.Future<_i13.NotificationAppLaunchDetails?>.value(),
          )
          as _i5.Future<_i13.NotificationAppLaunchDetails?>);

  @override
  _i5.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i14.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #show,
              [id, title, body, notificationDetails],
              {#payload: payload},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancel(int? id, {String? tag}) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [id], {#tag: tag}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i15.TZDateTime? scheduledDate,
    _i14.NotificationDetails? notificationDetails, {
    required _i16.UILocalNotificationDateInterpretation?
    uiLocalNotificationDateInterpretation,
    required _i17.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i18.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #zonedSchedule,
              [id, title, body, scheduledDate, notificationDetails],
              {
                #uiLocalNotificationDateInterpretation:
                    uiLocalNotificationDateInterpretation,
                #androidScheduleMode: androidScheduleMode,
                #payload: payload,
                #matchDateTimeComponents: matchDateTimeComponents,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i13.RepeatInterval? repeatInterval,
    _i14.NotificationDetails? notificationDetails, {
    required _i17.AndroidScheduleMode? androidScheduleMode,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShow,
              [id, title, body, repeatInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i14.NotificationDetails? notificationDetails, {
    _i17.AndroidScheduleMode? androidScheduleMode =
        _i17.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #periodicallyShowWithDuration,
              [id, title, body, repeatDurationInterval, notificationDetails],
              {#androidScheduleMode: androidScheduleMode, #payload: payload},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i13.PendingNotificationRequest>>
  pendingNotificationRequests() =>
      (super.noSuchMethod(
            Invocation.method(#pendingNotificationRequests, []),
            returnValue:
                _i5.Future<List<_i13.PendingNotificationRequest>>.value(
                  <_i13.PendingNotificationRequest>[],
                ),
          )
          as _i5.Future<List<_i13.PendingNotificationRequest>>);

  @override
  _i5.Future<List<_i13.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNotifications, []),
            returnValue: _i5.Future<List<_i13.ActiveNotification>>.value(
              <_i13.ActiveNotification>[],
            ),
          )
          as _i5.Future<List<_i13.ActiveNotification>>);
}
